# Generated by Django 3.1.7 on 2021-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_retweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweets',
        ),
        migrations.AddField(
            model_name='tweet',
            name='isRetweet',
            field=models.BooleanField(default=False),
        ),
    ]
