# Generated by Django 3.1.7 on 2021-05-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20210517_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweetKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
