# Generated by Django 3.1.7 on 2021-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='following',
        ),
        migrations.AddField(
            model_name='userdata',
            name='following',
            field=models.JSONField(default=list),
        ),
    ]
