# Generated by Django 3.1.7 on 2021-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210510_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
